version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: neetrino-postgres
    environment:
      POSTGRES_USER: neetrino_user
      POSTGRES_PASSWORD: neetrino_password
      POSTGRES_DB: neetrino_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neetrino_user -d neetrino_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: neetrino-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: neetrino-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://neetrino_user:neetrino_password@postgres:5432/neetrino_platform
      - REDIS_URL=redis://redis:6379
      - API_URL=http://api:3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: npm run dev

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: neetrino-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://neetrino_user:neetrino_password@postgres:5432/neetrino_platform
      - REDIS_URL=redis://redis:6379
      - PARSING_ENABLED=false
      - CHECKING_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  postgres_data:
  redis_data:
